/*****************************************
Course: IMT 577
Student: Urvi Chaudhary
Assignment: Module 8
Date: 05/22/2022

*****************************************/

USE IMT577_DW_URVI_CHAUDHARY;

CREATE OR REPLACE SECURE VIEW DIM_CHANNEL_V AS 
(
SELECT DIMCHANNELID, CHANNELID, CHANNELCATEGORYID, CHANNELNAME, CHANNELCATEGORY

FROM DIM_CHANNEL
);

CREATE OR REPLACE SECURE VIEW DIM_CUSTOMER_V AS
(
SELECT DIMCUSTOMERID, DIMLOCATIONID, CUSTOMERID, CUSTOMERFULLNAME, 
    CUSTOMERFIRSTNAME, CUSTOMERLASTNAME, CUSTOMERGENDER

FROM DIM_CUSTOMER  
);

CREATE OR REPLACE SECURE VIEW DIM_LOCATION_V AS
(
SELECT DIMLOCATIONID, ADDRESS, CITY, POSTALCODE, STATE_PROVINCE, COUNTRY

FROM DIM_LOCATION 
);

CREATE OR REPLACE SECURE VIEW DIM_PRODUCT_V AS
(
SELECT DIMPRODUCTID, PRODUCTID, PRODUCTTYPEID, PRODUCTCATEGORYID, PRODUCTNAME, PRODUCTTYPE, PRODUCTCATEGORY,
  PRODUCTRETAILPRICE, PRODUCTWHOLESALEPRICE, PRODUCTCOST, PRODUCTRETAILPROFIT, PRODUCTWHOLESALEUNITPROFIT,
  PRODUCTPROFITMARGINUNITPERCENT

FROM DIM_PRODUCT
);

CREATE OR REPLACE SECURE VIEW DIM_RESELLER_V AS
(
SELECT DIMRESELLERID, DIMLOCATIONID, RESELLERID, RESELLERNAME, CONTACTNAME, PHONENUMBER, EMAIL

FROM DIM_RESELLER
);

CREATE OR REPLACE SECURE VIEW DIM_STORE_V AS
(
SELECT DIMSTOREID, DIMLOCATIONID, STOREID, STORENUMBER, STOREMANAGER

FROM DIM_STORE
);

CREATE OR REPLACE SECURE VIEW FACT_SALESACTUAL_V AS
(
SELECT SOURCESALESHEADERID, SOURCESALESDETAILID, DIMPRODUCTID, DIMSTOREID, DIMRESELLERID, DIMCUSTOMERID, 
    DIMCHANNELID, DIMSALEDATEID, DIMLOCATIONID,
    SALEAMOUNT, SALEQUANTITY, SALEUNITPRICE, SALEEXTENDEDCOST, SALETOTALPROFIT

FROM FACT_SALESACTUAL
);

CREATE OR REPLACE SECURE VIEW FACT_PRODUCTSALESTARGET_V AS
(
SELECT DIMPRODUCTID, DIMTARGETDATEID, PRODUCTTARGETSALESQUANTITY

FROM FACT_PRODUCTSALESTARGET
);

CREATE OR REPLACE SECURE VIEW FACT_SRCSALESTARGET_V AS
(
SELECT DIMCHANNELID, DIMSTOREID, DIMRESELLERID, DIMTARGETDATEID, SALESTARGETAMOUNT

FROM FACT_SRCSALESTARGET
);

-----------------------------------------------------------------------------------------------------------------

--VIEW 1: QUESTION 2

CREATE OR REPLACE SECURE VIEW BONUS_SHARE_V AS
(
SELECT YEAR, STORENUMBER, PROFIT, SALE,
SUM(SALE) OVER (PARTITION BY YEAR) AS TOTAL_SALE,
ROUND((SALE/TOTAL_SALE), 2) AS PROPORTION,
ROUND
(
CASE WHEN YEAR = 2013 THEN 500000*(SALE/TOTAL_SALE)
    WHEN YEAR = 2014 THEN 400000*(SALE/TOTAL_SALE)
END, 2) AS BONUS_PROPORTION
FROM
(
SELECT D.Year, S.STORENUMBER,
SUM(FSA.SALEAMOUNT) AS SALE, 
SUM(FSA.SALETOTALPROFIT) AS PROFIT

FROM FACT_SALESACTUAL AS FSA
INNER JOIN DIM_STORE AS S ON FSA.DIMSTOREID = S.DIMSTOREID
INNER JOIN DIM_PRODUCT AS P ON FSA.DIMPRODUCTID = P.DIMPRODUCTID
INNER JOIN DIM_DATE AS D ON FSA.DIMSALEDATEID = D.DATE_PKEY
WHERE P.PRODUCTTYPE LIKE '%Casual' AND STORENUMBER IN (5, 8)
AND D.YEAR || D.MONTH_NUM_IN_YEAR NOT IN (201411, 201412)  
GROUP BY D.Year, S.STORENUMBER
)
ORDER BY YEAR, STORENUMBER
);

--SELECT * FROM BONUS_SHARE_V;

-----------------------------------------------------------------------------------------------------------------

--VIEW 2: QUESTION 3

CREATE OR REPLACE SECURE VIEW PRODUCT_SALES_V AS
(SELECT D.YEAR, S.STORENUMBER, D.DAY_NAME, 
AVG(FSA.SALEAMOUNT) AS AVG_SALESAMT,
SUM(FSA.SALEQUANTITY) AS QUANTITY, 
SUM(FSA.SALEAMOUNT) AS SALE, 
SUM(FSA.SALETOTALPROFIT) AS PROFIT

FROM FACT_SALESACTUAL AS FSA
INNER JOIN DIM_STORE AS S ON FSA.DIMSTOREID = S.DIMSTOREID
INNER JOIN DIM_DATE AS D ON D.DATE_PKEY = FSA.DIMSALEDATEID
INNER JOIN DIM_PRODUCT AS P ON P.DIMPRODUCTID = FSA.DIMPRODUCTID

WHERE S.STORENUMBER IN (5,8)
GROUP BY D.YEAR, FSA.DIMSTOREID, D.DAY_NAME, S.STORENUMBER
ORDER BY D.YEAR, FSA.DIMSTOREID, AVG_SALESAMT DESC);

--SELECT * FROM PRODUCT_SALES_V;

-----------------------------------------------------------------------------------------------------------------

--VIEW 3: QUESTION 4

CREATE OR REPLACE SECURE VIEW STATEWISE_PERFORMANCE_V AS
(SELECT D.YEAR, D.MONTH_NAME, L.STATE_PROVINCE, A.CNT_STORE, 
AVG(FSA.SALEAMOUNT) AS AVG_SALESAMT,
SUM(FSA.SALEQUANTITY) AS QUANTITY, 
SUM(FSA.SALEAMOUNT) AS SALE, 
SUM(FSA.SALETOTALPROFIT) AS PROFIT

FROM FACT_SALESACTUAL AS FSA
INNER JOIN DIM_STORE AS S ON FSA.DIMSTOREID = S.DIMSTOREID
INNER JOIN DIM_DATE AS D ON D.DATE_PKEY = FSA.DIMSALEDATEID
INNER JOIN DIM_LOCATION AS L ON S.DIMLOCATIONID = L.DIMLOCATIONID
INNER JOIN DIM_PRODUCT AS P ON FSA.DIMPRODUCTID = P.DIMPRODUCTID
INNER JOIN 
(
SELECT L.STATE_PROVINCE, COUNT(S.STORENUMBER) AS CNT_STORE
FROM DIM_STORE AS S
INNER JOIN DIM_LOCATION AS L ON S.DIMLOCATIONID = L.DIMLOCATIONID
WHERE L.STATE_PROVINCE <> 'Unknown'  
GROUP BY L.STATE_PROVINCE
) A ON L.STATE_PROVINCE = A.STATE_PROVINCE

WHERE L.STATE_PROVINCE <> 'Unknown'  
GROUP BY D.YEAR, D.MONTH_NAME, L.STATE_PROVINCE, A.CNT_STORE
ORDER BY D.YEAR, D.MONTH_NAME, A.CNT_STORE DESC
);

--SELECT * FROM STATEWISE_PERFORMANCE_V;

-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------





